"""Framework-independent domain entities."""

from werkcrew_ai.domain.models import (
    Availability,
    DecisionTraceEntry,
    Employee,
    JobRequest,
    JobRequirement,
    OwnerDecision,
    OwnerDecisionAction,
    OwnerDecisionGateStatus,
    PendingOwnerDecisionGate,
    PlanVariant,
    PlanningResult,
    PlanningWorkItem,
    PostVisitValidation,
    SiteMeasurement,
    SiteVisit,
    SiteVisitBrief,
    SiteVisitReport,
    ScheduledTask,
    Skill,
    Vehicle,
    WorkflowState,
)
from werkcrew_ai.domain.owner_decision import (
    OWNER_RESPONSE_FINGERPRINT_SCHEMA,
    PRICING_GATE_FINGERPRINT_SCHEMA,
    owner_response_fingerprint,
    pricing_gate_fingerprint,
)

__all__ = [
    "Availability",
    "DecisionTraceEntry",
    "Employee",
    "JobRequest",
    "JobRequirement",
    "OWNER_RESPONSE_FINGERPRINT_SCHEMA",
    "OwnerDecision",
    "OwnerDecisionAction",
    "OwnerDecisionGateStatus",
    "PRICING_GATE_FINGERPRINT_SCHEMA",
    "PendingOwnerDecisionGate",
    "PlanVariant",
    "PlanningResult",
    "PlanningWorkItem",
    "PostVisitValidation",
    "SiteMeasurement",
    "SiteVisit",
    "SiteVisitBrief",
    "SiteVisitReport",
    "ScheduledTask",
    "Skill",
    "Vehicle",
    "WorkflowState",
    "owner_response_fingerprint",
    "pricing_gate_fingerprint",
]
