"""Canonical durable M1 intake boundary."""

from werkcrew_ai.intake.lifecycle import (
    ACTIVITY_STATE_DIMENSION,
    FINGERPRINT_VERSION,
    AdapterReceipt,
    BindConversationOperation,
    CanonicalM1LifecycleService,
    CreateJobOperation,
    DormantReason,
    FactValidationKind,
    FollowUpEvidence,
    FollowUpFactCandidate,
    M1LifecycleEvent,
    M1LifecycleEventType,
    M1OperationEnvelope,
    M1OperationKind,
    M1OperationResult,
    M1OutcomeCode,
    MarkDormantOperation,
    RecordFollowUpOperation,
    WakeJobOperation,
    canonical_json,
    canonical_json_sha256,
    operation_fingerprint,
    operation_fingerprint_payload,
)
from werkcrew_ai.intake.models import (
    CanonicalFactInput,
    CanonicalJob,
    CanonicalJobActivity,
    CanonicalJobFact,
    CanonicalJobIntake,
    CanonicalJobLifecycle,
    FactKnowledgeState,
    FactVerificationState,
    JobFactName,
)
from werkcrew_ai.intake.normalization import normalize_job_intake
from werkcrew_ai.intake.repository import (
    CanonicalJobNotFoundError,
    CanonicalJobRepository,
    DuplicateCanonicalJobError,
    FactRevisionConflictError,
)

__all__ = [
    "ACTIVITY_STATE_DIMENSION",
    "FINGERPRINT_VERSION",
    "AdapterReceipt",
    "BindConversationOperation",
    "CanonicalFactInput",
    "CanonicalJob",
    "CanonicalJobActivity",
    "CanonicalJobFact",
    "CanonicalJobIntake",
    "CanonicalJobLifecycle",
    "CanonicalJobNotFoundError",
    "CanonicalJobRepository",
    "CanonicalM1LifecycleService",
    "CreateJobOperation",
    "DormantReason",
    "DuplicateCanonicalJobError",
    "FactKnowledgeState",
    "FactRevisionConflictError",
    "FactVerificationState",
    "FactValidationKind",
    "FollowUpEvidence",
    "FollowUpFactCandidate",
    "JobFactName",
    "M1LifecycleEvent",
    "M1LifecycleEventType",
    "M1OperationEnvelope",
    "M1OperationKind",
    "M1OperationResult",
    "M1OutcomeCode",
    "MarkDormantOperation",
    "RecordFollowUpOperation",
    "WakeJobOperation",
    "canonical_json",
    "canonical_json_sha256",
    "normalize_job_intake",
    "operation_fingerprint",
    "operation_fingerprint_payload",
]
