"""Public M8.0 frozen catalog/configuration API."""

from werkcrew_ai.catalog.chunking import (
    conditional_predecessor_chunk_ids,
    estimated_worker_hours,
    generate_job_item_chunks,
)
from werkcrew_ai.catalog.eligibility import exact_skill_level, is_worker_schedulable
from werkcrew_ai.catalog.m8_demo import (
    I18N_CATALOG_VERSION,
    M8_CONFIGURATION,
    SERVICE_CATALOG_VERSION,
    SKILL_MATRIX_VERSION,
    SKU_PLANNING_PROFILE_VERSION,
    VEHICLE_POLICY_VERSION,
)
from werkcrew_ai.catalog.models import (
    DATA_CLASSIFICATION_DEMO,
    EXPECTED_SKUS,
    CatalogLabel,
    ChunkedJobItem,
    ChunkingPolicy,
    ConfigurationIssue,
    CrewMember,
    CrewRole,
    M8BusinessConfiguration,
    ScheduledChunk,
    ServiceCatalogItem,
    SkillRating,
    SkuPlanningProfile,
    UnitDisplayAlias,
    UnitType,
    VehicleClass,
    VehicleKind,
    VehiclePolicy,
    VehiclePreference,
    VehicleProfile,
)
from werkcrew_ai.catalog.validation import (
    M8ConfigurationError,
    assert_valid_m8_configuration,
    validate_m8_configuration,
)

__all__ = [
    "DATA_CLASSIFICATION_DEMO",
    "EXPECTED_SKUS",
    "SERVICE_CATALOG_VERSION",
    "SKU_PLANNING_PROFILE_VERSION",
    "SKILL_MATRIX_VERSION",
    "VEHICLE_POLICY_VERSION",
    "I18N_CATALOG_VERSION",
    "M8_CONFIGURATION",
    "UnitType",
    "VehicleClass",
    "CrewRole",
    "VehicleKind",
    "UnitDisplayAlias",
    "ServiceCatalogItem",
    "SkuPlanningProfile",
    "SkillRating",
    "CrewMember",
    "VehicleProfile",
    "VehiclePreference",
    "VehiclePolicy",
    "CatalogLabel",
    "ChunkingPolicy",
    "M8BusinessConfiguration",
    "ScheduledChunk",
    "ChunkedJobItem",
    "ConfigurationIssue",
    "M8ConfigurationError",
    "validate_m8_configuration",
    "assert_valid_m8_configuration",
    "estimated_worker_hours",
    "generate_job_item_chunks",
    "conditional_predecessor_chunk_ids",
    "exact_skill_level",
    "is_worker_schedulable",
]
